### ISSUE TITLE
Option to only obfuscate Classes in Projects namespace

### ISSUE THREAD

**Issue by TK200KM** [mnestorov/php-obfuscator#2]
for my usage it would be great to have the option to obfuscate Classes properties, methods and constants of my project. 
f.i. : class method XYZ->doIT is called in script abc and in that script the string-expression of the property should be the same like in the obfuscated class

now i get "file/function/method/property notfound" or i only can use "goto" and string obfuscation

if methodname is changed from XYZ->doIt  to XYZ->dontDoThat the script must call $class =  XYZ->dontDoThat  instead of $class= XYZ->doIt 
the behavior with constants and properties should be the same in the projects namespace

Classes/Functions/Constants outside projects namespace should not be changed 

Is this possible?

**Comment by mnestorov** [comment]
Hey,

Please download/pull the latest version where I have implemented **custom obfuscation options**. This allows users to choose from different obfuscation options (e.g., obfuscating variable names, function names, or class names) or combine multiple options. See if these changes would work for you.

Regards,
Martin
